### ISSUE TITLE
Tweak “Show info” content

### ISSUE THREAD

**Issue by hidde** [w3c/wai-wcag-em-report-tool#10]
(From BJ)

In Step 2: Explore the Target Website / Section: Web Technologies Relied Upon, it explains how to add, but the mechanism has changed. This needs updating to reflect how it works now.

In Step 2: Explore the Target Website / Section: Web Technology: CSS and HTML are listed as examples, but they are already there by default.

**Comment by nitedog** [comment]
There are actually 2 "show info" for this widget (the second one is for "Web Technology"). I think the content for both these "show info" will depend on how you resolve issue #8. @hidde let's discuss when we meet on Thursday.

**Comment by hidde** [comment]
The 'Note' in the first Show Info has been removed. The second 'Show info' was removed altogether as the updated UI should be more obvious and no longer require this level of guidance.
