### ISSUE TITLE
Document the format we expect to work with “Import EARL as JSON”

### ISSUE THREAD

**Issue by hidde** [w3c/wai-wcag-em-report-tool#12]
cc @nitedog 

There's currently no way to know:

* as a user, if “Import as EARL” will work with a given tool.
* as a vendor of automated accessibility tooling, if “Import as EARL” will work with my tool or what I need to do to make that happen

**Comment by hidde** [comment]
Hidde and Shadi discussed 13 July: we'll add this in the [Wiki page](https://github.com/w3c/wai-wcag-e-report-tool/wiki/Import-Function). 

Hidde and Michel discussed 14 July: should try to describe which tools it will work with.

**Comment by hidde** [comment]
Another open issue: what to do when an import contains issues that are: 

* related to WCAG criterium that is not in scope
* related to no WCAG criteriia (eg 'best practices')

If they display, where would that be?

**Comment by nitedog** [comment]
added [documentation](https://github.com/w3c/wai-wcag-em-report-tool/wiki/How-to-use-the-%E2%80%9CAdd-data-from-other-(automated)-tests%E2%80%9D-functionality), please let me know what you think

**Comment by hidde** [comment]
I like it and think it is (more than) sufficient as an explanation.

One thing I feel users would expect is information on where to get a “data file from automated tool in EARL/JSON-LD format”. If we can do anything like “for example, an export from Tool X, version a or Tool Y, version b“, maybe even with disclaimer that it only worked with those tools at the time of writing, that would be very helpful I think.

**Comment by hidde** [comment]
Documentation now exists, we can improve it when we get to it, closing this issue for now.
