### ISSUE TITLE
Problem with duplicated data in .json file

### ISSUE THREAD

**Issue by miranausnerffg** [w3c/wai-wcag-em-report-tool#124]
In some cases, the results for the entire sample are duplicated. They are present twice in the .json and are also displayed twice under "View Report". We noticed it on a website with a large number of sub-pages in the sample. Could the error possibly be related to insufficient browser resources when opening or saving the .json?

**Comment by iadawn** [comment]
Related to #111

**Comment by iadawn** [comment]
@miranausnerffg Would you have a screen shot of what this looks like? I am struggling to replicate and so can't really be sure of what I am looking for.

**Comment by miranausnerffg** [comment]
Sent screenshots via email to @iadawn because of privacy reasons.

**Comment by MarkoTodorovicFFG** [comment]
When a sample is deleted, the [handleSampleDelete function](https://github.com/w3c/wai-wcag-em-report-tool/blob/67e6cec68c668280e832392f9f5f4b5bf7884c06/src/components/form/SampleInput/SampleInput.svelte#LL112C2-L124C2) of SampleInput.svelte is called, but after testing it seems that related assertions are _not_ deleted.

When another new sample is added, an ID is given to the new sample. This ID can be the same as the ID of the previously deleted sample, and thus the previous assertions are now related to this new sample by its ID. Additionally, new assertions are created and reference the same ID. The result being one sample page, with multiple sets of related assertions.

One possible solution would be to delete assertions that reference a sample by ID, when deleting the sample itself.
First, import assertions from assertionStore:
```javascript
import assertions from '@app/stores/earl/assertionStore/index.js';
```
This code could then be called in the handleSampleDelete function:
```javascript
$assertions = $assertions.filter(assertion => assertion.subject.id !== removeSample.id);
```
Maybe there is a neater way of doing this.

**Comment by mhansma96** [comment]
@MarkoTodorovicFFG Thanks for sharing. I have made a PR #134 with these changes. You can also find a preview here: https://deploy-preview-134--wcag-em-report-tool-2021-redesign.netlify.app/ 
Could you maybe check it out and test it to see if some result is improved. Maybe we can go from there :)

**Comment by miranausnerffg** [comment]
Guten Tag,

danke für Ihre Nachricht. Ich bin bis 17.11.2023 nicht erreichbar. Ihre E-Mail wird nicht automatisch weitergeleitet, ich bearbeite die eingelangten Nachrichten nach meiner Rückkehr.

Freundliche Grüße,
Mira Nausner
 
FFG Österreichische Forschungsförderungsgesellschaft
Expertin Digitale Barrierefreiheit 
Sensengasse 1, 1090 Wien
Tel: +43-(0)5 77 55-7124
Fax: +43-(0)5 77 55-95001
E-Mail: ***@***.*** 
http://www.ffg.at 
******************************************************************************************************************************
Innovationen verbinden. Vernetzen Sie sich mit uns auch auf Linkedin!
FFG Disclaimer / Legal notice: http://www.ffg.at/Disclaimer
******************************************************************************************************************************

**Comment by MarkoTodorovicFFG** [comment]
Our testing of the PR suggests that this solves the problem.

**Comment by mhansma96** [comment]
@iadawn FYI, I saw you already did some cleaning up on the PR regarding this issue, but see the comments above. Looks like we made some improvements!

**Comment by iadawn** [comment]
Perfect. I will include this in the WCAG 2.2 publication that we are just working though
