### ISSUE TITLE
Corrupted JSON data

### ISSUE THREAD

**Issue by lattegirrl** [w3c/wai-wcag-em-report-tool#128]
I'm constantly losing JSON data in the report each time I open the report.  I have at least six (6) defined Structured Sample Web Pages and I saved my updates often using Ctrl+S or Download Report (JSON). 

The data appears correct in HTML when I use Download Report (HTML). 

When I open the JSON report, it is only showing 2 out of the 6 structured samples and shows duplicate entires. The HTML output is correct. 

![report_json](https://github.com/w3c/wai-wcag-em-report-tool/assets/19654546/9b2de985-0691-451c-a45c-e50268449ddb)
![report_html](https://github.com/w3c/wai-wcag-em-report-tool/assets/19654546/7aa55890-a12c-41ce-9bf9-29531f54f09b)
![structured_samples](https://github.com/w3c/wai-wcag-em-report-tool/assets/19654546/6854bceb-943c-4e44-9970-6d740dede9ce)

**Comment by iadawn** [comment]
This appears to have been addressed with the latest batch of fixes. If the problem persists, please do reopen the issue
