### ISSUE TITLE
🚀 Deploy the redesign

### ISSUE THREAD

**Issue by hidde** [w3c/wai-wcag-em-report-tool#13]
## Making the switch in code

- ~Ensure routing works (can look at how it is done in ATAG Report Tool); the tool will likely live on a sub URI of `w3.org/WAI`, we should make sure paths continue to work~ done
- ~Will we reverse proxy to GitHub Pages like we do for ATAG Report Tool, or some other mechanism?~ yes 

## Comms

- ~Add banner to old tool announcing date some time before~ done

**Comment by hidde** [comment]
Depending on an environment variable, some script should throw in either `''` or `/WAI/eval/report-tool`, depending on whether it is building for GH Pages (where we'll deploy) or Netlify/development enviornment.

In ATAG Report Tool, we do this by [running, Mustache differently for each env](https://github.com/w3c/wai-atag-report-tool/blob/main/package.json#L35) and then using a different config file for each ([config files](https://github.com/w3c/wai-atag-report-tool/tree/main/config)).

**Comment by shawna-slh** [comment]
* [ ] update https://github.com/w3c/wai-wcag-em-report-tool/wiki/What's-new-in-the-2021-redesign e.g.:
> you can find the differences between what's currently live and what is in the new 2021 version

**Comment by hidde** [comment]
All the pre-deployment tasks are done. Last task:

* [ ] Add rewrite rule that effective causes `/WAI/eval/report-tool` to serve the new version

**Comment by shawna-slh** [comment]
Hi @hidde

* [ ] I think also need to change the banner on the previous version? https://github.com/w3c/wai-wcag-em-report-tool/issues/48 might have old wording. Let me know if we need to synch up on updated wording.

**Comment by hidde** [comment]
It's all deployed now! 👍🏻
