### ISSUE TITLE
SC 3.3.9 is not displayed

### ISSUE THREAD

**Issue by remibetin** [w3c/wai-wcag-em-report-tool#144]
**Describe the bug**
The Success Criterion 3.3.9 is not displayed in the WCAG-EM Report Tool, although present in https://github.com/w3c/wai-wcag-em-report-tool/blob/main/src/data/wcag.json & https://github.com/w3c/wai-wcag-em-report-tool/blob/main/src/locales/en/WCAG.json

**To Reproduce**
1. Go to [WCAG EM Report Tool](https://www.w3.org/WAI/eval/report-tool/evaluation/)
2. Click on "4: Audit Sample" step link.
3. Make sure the WCAG version selected is WCAG 2.2.
4. Scroll down to "3.3 Input Assistance" and look for 3.3.9 Success Criterion. See it is not displayed.

**Expected behavior**

SC 3.3.9 is displayed in the "3.3. Input Assistance" section (in "4. Audit Sample" & "View Report" pages) when scope is WCAG 2.2.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: 120.0.6099.129

**Additional context**
SC 3.3.9 is the last SC in the https://github.com/w3c/wai-wcag-em-report-tool/blob/main/src/data/wcag.json & https://github.com/w3c/wai-wcag-em-report-tool/blob/main/src/locales/en/WCAG.json files

**Comment by remibetin** [comment]
@iadawn

**Comment by BartCardan** [comment]
3.3.9 is on level AAA. Make sure you select Conformance target AAA in step 1 to see this SC.

**Comment by remibetin** [comment]
@BartCardan Thank you so much, my bad. It works indeed.
