### ISSUE TITLE
Delete icon not displaying on sample page

### ISSUE THREAD

**Issue by chronoDave** [w3c/wai-wcag-em-report-tool#151]
**Describe the bug**
Delete icon on sample page is not showing on Firefox

**To Reproduce**
1. Create a new report
2. Navigate to Step 3: Select a Representative Sample
3. Add new web page using "Add web page"
4. Sample page is not showing the delete icon

**Expected behavior**
I'm expecting the delete icon to be visible so I can delete a sample page.

**Screenshots**
![image](https://github.com/w3c/wai-wcag-em-report-tool/assets/27073716/44f73c35-3f72-49d9-8f00-a44ccd05c65f)
![image](https://github.com/w3c/wai-wcag-em-report-tool/assets/27073716/562aa24e-89cf-4411-ad29-2a283a0072be)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 122.0

**Additional context**
I can create a PR to fix this issue, it seems trivial to fix.

**Comment by iadawn** [comment]
Hi @chronoDave, would welcome a PR for this if you have the time
