### ISSUE TITLE
Cleanup warnings

### ISSUE THREAD

**Issue by mhansma96** [w3c/wai-wcag-em-report-tool#16]
There are some warnings that we might be able to get rid of quite easily.

On opening the tool:
![image](https://user-images.githubusercontent.com/84068842/123955777-4a59d100-d9aa-11eb-939b-53d70f773382.png)

After starting the tool in the console:
![image](https://user-images.githubusercontent.com/84068842/123955868-6b222680-d9aa-11eb-9dad-2ac529392beb.png)

**Comment by hidde** [comment]
Thanks, yes, great to address these.

Re the `on:blur`/`on:change`: we changed that before and it seemed to break syncing the data, happy for you to check it again, as you've seen so much of the data bits now!
