### ISSUE TITLE
Installation on a private server

### ISSUE THREAD

**Issue by ChrisHollowayAccessibility** [w3c/wai-wcag-em-report-tool#166]
Hi I was wondering if it is ok to install this on a private server behind a login page rather than locally and if so are there any instructions on how to do so.

**Comment by iadawn** [comment]
Hi @ChrisHollowayAccessibility,

Absolutely no problem installing this on a private server. There is information available about [Permissions to Use](https://www.w3.org/WAI/about/using-wai-material/). 

There are some instructions in the [README](https://github.com/w3c/wai-wcag-em-report-tool?tab=readme-ov-file#readme) about how to install the product locally.

If there are any specific questions or suggestions to improve the instructions please do reopen this issue.

Thanks

Kevin
