### ISSUE TITLE
Also show warning before performing 'Start new report' action

### ISSUE THREAD

**Issue by hidde** [w3c/wai-wcag-em-report-tool#18]
comment from @nitedog 

we have a warning when you do 'Clear report', we should also show one when doing 'Start new report'

**Comment by hidde** [comment]
@mhansma96 do you feel like taking this one on?

**Comment by mhansma96** [comment]
Sure. Assigned!

**Comment by hidde** [comment]
Warning message before starting a new report is now live! Thanks @mhansma96! https://wcag-em-report-tool-2021-redesign.netlify.app/
