### ISSUE TITLE
"Show info" buttons appear before their related fields in tab order

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-wcag-em-report-tool#3]
When navigating with the tab it may be distracting to have the "Show info" before the field itself. Should they appear before or after in tab order.

**Comment by hidde** [comment]
Thanks! Looks like we can do this with some CSS (would like to avoid `tabindex` everywhere).

Do we also want this for 'View Report' link in the Observations textareas when auditing a sample?

**Comment by hidde** [comment]
Tab order is now fixed, also for 'View report' links, they now come after the observations field they are about.
