### ISSUE TITLE
Some titles are cut off in Dutch translation on View Report page

### ISSUE THREAD

**Issue by mhansma96** [w3c/wai-wcag-em-report-tool#30]
It seems like something goes wrong with the processing of these translations as they get cut off after whitespaces

See image:
![image](https://user-images.githubusercontent.com/84068842/124775763-2dd80e80-df3f-11eb-8bba-0e0fc954003d.png)

**Comment by hidde** [comment]
Fixed in https://github.com/w3c/wai-wcag-em-report-tool/pull/31, thanks (again) @mhansma96 !
