### ISSUE TITLE
Sample title out of bounds when to long

### ISSUE THREAD

**Issue by mhansma96** [w3c/wai-wcag-em-report-tool#32]
When you add a sample with a very long title it will go out of bounds and it won't get snapped. When using a long title with spaces, this is not a problem.

See image:
![image](https://user-images.githubusercontent.com/84068842/125284950-5c2c6400-e31a-11eb-8e7e-0509dc2d8085.png)

**Comment by hidde** [comment]
Fixed in https://github.com/w3c/wai-wcag-em-report-tool/pull/31, thank you @mhansma96 !
