### ISSUE TITLE
Sticky Your Report block can overlap results on Report Findings page

### ISSUE THREAD

**Issue by mhansma96** [w3c/wai-wcag-em-report-tool#33]
![image](https://user-images.githubusercontent.com/84068842/125287519-4cfae580-e31d-11eb-82d7-b1b855df89eb.png)

**Comment by mhansma96** [comment]
We can "wrap" the text in findings. This:

- will make the layout consistent with other pages
- leaves the Your Report block sticky and always visible

We can "unstick" the Your Report block. This:

- will probably also unstick it on the Audit Sample page
- leave more space for text in findings

Any thoughts @hidde ?

**Comment by hidde** [comment]
Ah, sorry, this box is not supposed to show on the View Report page.

Let's remove it there. While we're at it, we can probably improve 'show panel' logic. 

Overview:
 
No panel: Overview, Acknowledgements, View Report
Panel: all other pages

“No panel” means the panel should not render, but also that the 'full width' grid should (eg the grid that does not leave space for a panel).
