### ISSUE TITLE
Add WCAG-EM Report Tool version number to output JSON

### ISSUE THREAD

**Issue by hidde** [w3c/wai-wcag-em-report-tool#35]
(This was requested by someone who builds a tool that uses WCAG-EM Report Tool output)

**Comment by mhansma96** [comment]
Is it this version? @hidde 
![image](https://user-images.githubusercontent.com/84068842/125297167-4bceb600-e327-11eb-97cf-30971f3fcdf1.png)

This is from a report generated with the new tool

**Comment by hidde** [comment]
No, the version of the tool, sorry for misunderstanding. So it is this number:

https://github.com/w3c/wai-wcag-em-report-tool/blob/main/package.json#L3

**Comment by hidde** [comment]
fixed in https://github.com/w3c/wai-wcag-em-report-tool/pull/31 thanks @mhansma96 !
