### ISSUE TITLE
Overview of audit results - data entry?

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-wcag-em-report-tool#39]
[!!]
Location: View Report page

On the View Report page, the fourth heading down is "Overview of audit results." I cannot find where that data would be entered. I have looked through all the steps and filled in all of the data fields (except all of the success criteria outcomes and observations) and can't seem to get that heading populated in the view report page. All it says is "Not Provided." There is no "edit" button on that section either to edit it directly on that page. 

Am I missing something? If that is no longer being used for data, then that heading needs to be removed.

**Comment by hidde** [comment]
Thanks for spotting this, @bakkenb ! Have removed this section, you are right, it is no longer used!
