### ISSUE TITLE
'This page in' string may be difficult to understand

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-wcag-em-report-tool#4]
"This page in" may be difficult to understand for some. Why not use "Languages and Translations" as in other WAI templates?

**Comment by shawna-slh** [comment]
Hi @hidde and @daniel-montalvo 

Indeed this is a site-wide issue. I added it to : https://github.com/w3c/wai-website/issues/264

If you think it should be higher priority, let me know.
