### ISSUE TITLE
Step 4 - Show full description link

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-wcag-em-report-tool#40]
[ED - Med] Step 4: Audit Sample

Each Success Criteria has a "Show full description" link. For the longer success criteria this is great because you can activate the button to show the full language. 

Many success criteria don't have any more detail in the description than what is already loaded on screen by default. The button is still there and doesn't do anything which can be confusing. Can that button be removed or hidden in the cases when it is not needed because all the detail is already showing?

**Comment by hidde** [comment]
Thanks Brent, have fixed this issue in https://github.com/w3c/wai-wcag-em-report-tool/issues/43. Looks like the `if` statement we used for this broke somehow, causing the button to always display.
