### ISSUE TITLE
Structured Report link seems wrong

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-wcag-em-report-tool#41]
[!!]
Location: Overview Page / About This Tool

The link to "Structured Report" goes to the current report tool View Report page. Should that link be going somewhere else, like to the new View Report page?

**Comment by hidde** [comment]
Yes! Good catch.

Have updated the URL to match what it would be in the new tool (`w3.org/WAI/eval/report-tool/evaluation/view-report`)
