### ISSUE TITLE
[ED-low] Links to Step 5 do not move view to top of viewport

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-wcag-em-report-tool#42]
**Describe the bug**
Following the links to Step 5 do not move view to top of viewport.
The links to other steps move the viewport to the top. The links to step 5 (from step 4 or step 6) do not.

**To Reproduce**
1. Go to Step 4 or Step 6 
2. Click on 'Report Findings' in the navigation bar at the bottom of the page
3. Step 5 load but the viewport does not move to the top

**Expected behavior**
For every other step the viewport moves to the top. It should move also in this step.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 
 - Browser: Safari
 - Version 14.1.1 (16611.2.7.1.4)

**Comment by hidde** [comment]
Thanks for filing this. 

Have reproduced in Safari, could not reproduce in Firefox or Chromium.

The background to this is that these are not actual pages or loading of pages, we're trying to mimick browser navigation behavior.

**Comment by hidde** [comment]
Looks like this happened because not all success criteria were fully loaded when the navigation code ran, have just fixed.
