### ISSUE TITLE
[ED-low] Consider not presenting the "Show full description" button when there is no extra description to show 

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-wcag-em-report-tool#43]
On step 4, every Success Criteria includes a "Show full description" button after the first paragraph of the SC's description. Most SC only have one paragraph, and the button does not show additional content when activated. This might confuse users. 
Consider not presenting the "Show full description" button when there is no extra description to show.

This is not exactly a bug, but there is no category to submit suggestions.

**Comment by hidde** [comment]
Thanks @carlosapaduarte ! Have just fixed this, looks like the conditional statement we had there no longer worked.
