### ISSUE TITLE
Ctrl +s to save functionality does not work

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-wcag-em-report-tool#44]
I recall some discussion on this although I can't remember the resolution. Having just completed an audit using the existing reporting tool, this functionality is essential! Especially considering the issues with local storage, working on multiple projects, working with multiple auditors.

Not sure if this has been removed or simply does not work in Edge. Currently when I press ctrl+s I get the webpage save dialog which will save the HTML not the JSON.

**Comment by hidde** [comment]
Hey Kevin, will investigate happened here, as after our discussion about this, we did add the functionality  for CTRL+S (Windows) and CMD+S (Mac), and I can say, as they say, “it worked on my machine at the time”.  Will get back to you!

**Comment by hidde** [comment]
This has now been fixed! Thanks again for filing it, @iadawn !
