### ISSUE TITLE
Step 4 - add link to more info on EARL/JSON

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-wcag-em-report-tool#5]
Will you add a link from the "Add data from other (automated) tests" box to documentation on GitHub (or elsewhere) about this import functionality?

**Comment by nitedog** [comment]
Please link to this wiki page for now: https://github.com/w3c/wai-wcag-em-report-tool/wiki/Import-Function

**Comment by hidde** [comment]
This link was just added! Closing this issue, let's continue the work (filling in the wiki page) in https://github.com/w3c/wai-wcag-em-report-tool/issues/12
