### ISSUE TITLE
Filename depending on website name

### ISSUE THREAD

**Issue by julezrulez** [w3c/wai-wcag-em-report-tool#52]
Currently with Cltr+S the file is saved end gets the name 'evaluation.json'

In the old report tool when saving a file the filename gets the 'Website name' prefixed (all in lower case and spaces and strange characters turned into dashes). When doing a lot of audits or doing more audits at the same time your download folder gets filled with saved files. By adding the website name  to these file names you could easily distinguish the different audits.
So for my website named "200 OK" at 200ok.nl the file name would be: 200-ok-evaluation.json

**Comment by hidde** [comment]
Have done this for JSON and HTML file names!
