### ISSUE TITLE
Show your report button transparency and z-index

### ISSUE THREAD

**Issue by Aircl0wn** [w3c/wai-wcag-em-report-tool#57]
When creating a report and hiding the “Your report” summary on the right side, a button “Show your report” becomes available.
The button has a fixed position when scrolling down the page.

Because the button is transparent, it mingles with other text on its path.
It also goes behind the “Import data EARL/JSON” button.

https://user-images.githubusercontent.com/13189457/129254009-6dcf64f8-be13-4507-abcc-8d65d431d49c.mov

**Comment by hidde** [comment]
Thanks Ronny, have fixed this by making it non-sticky when the Your report box is hidden.
