### ISSUE TITLE
HTML report not nested correctly HEAD / BODY and missing files

### ISSUE THREAD

**Issue by BartCardan** [w3c/wai-wcag-em-report-tool#59]
**Describe the bug**
When a HTML report is downloaded in step 'View report' the HTML report is not nested correctly. For example it contains a double title-element and meta-elements outside the HEAD. 
Also lang attribuut on HTML element is missing.
HTML report has references to files which are missing:
- /bundles/global.css
- /bundles/main.css
- /bundles/main.js
- /images/favicon.ico
The column "Edit" shouldn't be exported to the HTML report download.

See code:
I've tried to add the code, but it's not showing correctly (Github will remove part of the code). I've added a screenshot of the code instead. 
![screenshot-1](https://user-images.githubusercontent.com/84503290/129317619-2814511f-1915-4580-aef4-4fd68744c94a.png)

**To Reproduce**
1. Skip all steps and go directly to  'View Report' (latest step)
2. Click on button 'Download Report (HTML)'
3. Open the downloaded report.html file
4. Open source code.

**Expected behavior**
Correct nested HTML report which has correct doc language.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 92.0.4515.131

**Comment by hidde** [comment]
Thanks for filing this, Bart. We recently overhauled how this functionality works and it seems we made some mistakes.

**Comment by hidde** [comment]
This has been fixed. In the latest version we've cleaned up the HTML, added the appropriate `lang` attribute and removed external sources. Thanks again for reporting, @BartCardan !
