### ISSUE TITLE
HTML report add informtion from Chrome extensions

### ISSUE THREAD

**Issue by BartCardan** [w3c/wai-wcag-em-report-tool#60]
**Describe the bug**
I am using a Chrome extension to show the IP-address of websites in the browser. It's done by adding the IP-address dynamically in the source of the website. 
When downloading the HTML report this IP-address is also added to the downloaded HTML-file. 

**To Reproduce**
1. Go to https://chrome.google.com/webstore/detail/showip/agoljmemkbciolpigpabjfkagboolkcj and install extension in Chrome
2. Go to report tool step 'View report'
3. Click on button 'Download report (HTML)'
4. Open downloaded report file
3. Scroll down to the button
4. See IP-address

**Expected behavior**
I don't know if this also happens with other browsers extensions, but it might be good to have a look at this. Testers use a lot of extensions which may output something in the downloaded report. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 92

**Comment by hidde** [comment]
Thanks for this report!

If you use extensions that modify HTML, they will show up in the output. To mitigate your issue, I would suggest creating the report in a clean browser, perhaps in a private tab that extensions don't have access to. 

For now, we don't have bandwidth to reimplement this functionality in a way that does not rely on the browser. You would be more than welcome to submit a pull request that reimplements the HTML download functionality, let me know and I will happily reopen this issue for you.
