### ISSUE TITLE
First example report not working

### ISSUE THREAD

**Issue by BartCardan** [w3c/wai-wcag-em-report-tool#61]
**Describe the bug**
When testing the first example report from https://github.com/w3c/wai-wcag-em-report-tool/wiki/Example-report I get a javascript error (see below) and no report data. JSON file from evaluation see: https://technobility.nl/tests/evaluation.json

`Uncaught (in promise) TypeError: p.match is not a function
    at Object.Kh.e.$$.update (Textarea.svelte:23)
    at ze (index.mjs:1458)
    at new n (Textarea.svelte:20)
    at Array.mv (DefineScopePage.svelte:26)
    at P (index.mjs:61)
    at Array._d (Page.svelte:20)
    at wd (Page.svelte:6)
    at ze (index.mjs:1462)
    at new n (Page.svelte:58)
    at gv (DefineScopePage.svelte:65)`

**To Reproduce**
1. Go to https://github.com/w3c/wai-wcag-em-report-tool/wiki/Example-report
2. Save the JSON data from the first example to a new json file.
3. Go to WCAG-EM Tool, first page
4. Click on button 'Open report' and select the json file.
5. See error

**Expected behavior**
I expect all example json works correctly. Maybe a warning can be shown if the json file is not correct?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 92

**Comment by hidde** [comment]
Thanks, have removed the first example report!
