### ISSUE TITLE
Recording of evaluation specifics not in JSON

### ISSUE THREAD

**Issue by BartCardan** [w3c/wai-wcag-em-report-tool#64]
**Describe the bug**
Content of "Recording of evaluation specifics" is not available in JSON. In JSON under reportFindings there is a key called "evaluationSpecifics" but it's always empty.

**To Reproduce**
1. Go to 'Step 5 Report Findings'
2. Enter something in textarea "Record of evaluation specifics (optional)"
3. Go to "View report" (Step 6)
4. Download JSON
5. Open JSON, no content of Record of Evaluation specifics textarea is available.

**Expected behavior**
As "Record of evaluation specifics" is used to record the evaluation tools, web browsers, assistive technologies, etc" it's the best place to enter used browsers including version numbers. When the JSON is used to import the report data (for example for automation) it's necessary to have this data.

**Comment by hidde** [comment]
Thanks @BartCardan for reporting, this should be fixed now!
