### ISSUE TITLE
Add language: Français

### ISSUE THREAD

**Issue by ericporlier** [w3c/wai-wcag-em-report-tool#80]
* [ ] Add language to list of languages (in [`src/locales/index.json`](https://github.com/w3c/wai-wcag-em-report-tool/blob/main/src/locales/index.json))
* [ ] Add folder with UI translations (in [`src/locales/[your-language]`](https://github.com/w3c/wai-wcag-em-report-tool/blob/main/src/locales))
* [ ] Add translation of WCAG in supported versions (in [`src/locales/[your-language]/WCAG.json`](https://github.com/w3c/wai-wcag-em-report-tool/blob/main/src/locales))

(Full documentation on [How to add a language](https://github.com/w3c/wai-wcag-em-report-tool/wiki/How-to-add-a-language))

**Comment by andypillip** [comment]
Bonjour @ericporlier .

Did you already download sources and start a local server? I'm having the issue that switching to German  doesn't work. When switching to _de_ in the language menu, it's actually using the texts from en/. With the already existing _nl_ it works. Does it work with _fr_ for you? Thanks.

Maybe @hidde can help?

**Comment by andypillip** [comment]
Actually @ericporlier , you will need to add `register('fr', () => import('../locales/translations_fr.json'));` to _src/scripts/i18n.js_ right below the other similar lines in addition to the steps described in the wiki.

**Comment by ericporlier** [comment]
> 
> 
> Actually @ericporlier , you will need to add `register('fr', () => import('../locales/translations_fr.json'));` to _src/scripts/i18n.js_ right below the other similar lines in addition to the steps described in the wiki.

Thank you @andypillip , info much appreciated.

**Comment by remibetin** [comment]
A French translation has been published! See https://github.com/w3c/wai-translations/issues/76 for context. Therefore, I am closing this issue.
