### ISSUE TITLE
The ability to include screenshots

### ISSUE THREAD

**Issue by sophieschoice** [w3c/wai-wcag-em-report-tool#86]
As an auditor it would be nice if there was a way to add screenshots to illustrate the issue that was found.

**Comment by hidde** [comment]
As the tool supports Markdown, you can add screenshots. You would have to host them somewhere on a server and can add them with this syntax: 

```markdown
![Alt text](https://your-website.com/your-screenshot.png)
```

We are unable to host your images for you, as we want to keep your data on your machine.
