### ISSUE TITLE
Document translations

### ISSUE THREAD

**Issue by hidde** [w3c/wai-wcag-em-report-tool#9]
* [x] Find out how translations work and what is needed: which files does someone need to change/update?
* [x] Check what's still relevant from [translations.md](https://github.com/w3c/wai-wcag-em-report-tool/blob/main/docs/translations.md), move any relevant content to the wiki
* [x] Clean up [translations.md](https://github.com/w3c/wai-wcag-em-report-tool/blob/main/docs/translations.md)
* [x] Document how translations can be submitted (what does a PR for a  translation look like) in [How to add a translation](https://github.com/w3c/wai-wcag-em-report-tool/wiki/How-to-add-a-language)
* [x] Make documentation easy to find (maybe as an Issue template and in the Wiki, with README pointing at the Wiki)

(example of [issue template implementation](https://github.com/hidde/eleventy-wcag-reporter/blob/main/.github/ISSUE_TEMPLATE/add-language-support.md))

**Comment by hidde** [comment]
Added [wiki page](https://github.com/w3c/wai-wcag-em-report-tool/wiki/How-to-add-a-language) and a [Pinned Issue](https://github.com/w3c/wai-wcag-em-report-tool/issues/23) in case people look there.

**Comment by mhansma96** [comment]
I've created a document based on my trying to add another language and making changes. Seems like it's not that difficult. I've added some comments and ideas on what we should try to communicatie if we make a step-by-step list or guide on the wiki.

[Adding a new language v0.1.docx](https://github.com/w3c/wai-wcag-em-report-tool/files/6769128/Adding.a.new.language.v0.1.docx)

Any ideas, thoughts or experimenting with the steps is welcome :)

**Comment by hidde** [comment]
Thanks for creating this doc, have had a look, let's discuss next steps tomorrow!

**Comment by hidde** [comment]
Discussed with @mhansma96 today; we like the clear steps in the table, the headings in wiki may also help.  Generally feel this guidance should be very specific and clear.

Hidde to merge those two ideas into one docs page and ask feedback from @shawna-slh, who is head of WAI translations.

**Comment by mhansma96** [comment]
Open question: how do we validate the quality of a translation or translator? Since we might not all be able to understand the language properly, we have to find out somehow if the translation is usable.

**Comment by hidde** [comment]
Closing this as documentation exists.
