### ISSUE TITLE
I'm not able to upload the report examples given in this wiki in step 4

### ISSUE THREAD

**Issue by Itusil** [w3c/wai-wcag-em-report-tool#99]
Hi,

I downloaded the example of a JSON-LD report from the wiki link (https://github.com/w3c/wai-wcag-em-report-tool/wiki/Example-report) and when I try to upload the JSON in the step 4 on the "import data from automated tests" I obtain an error saying "None of the assertions of this file match the selected sample". 

I'm new on this and I don't really know why it doesn't work. I undertand that this example report is a example of what reports does the importer allow, no?. What information should I change in the example of the JSON for it being accepted by the importer?

Thanks for the help.

![1](https://user-images.githubusercontent.com/42912862/154306986-0d97018a-30af-4712-b0e2-f67d79daecf3.jpg)

**Comment by shawna-slh** [comment]
Hi @Itusil 
You can "upload" or "import" the JSON from the first page:
&nbsp;&nbsp;&nbsp; https://www.w3.org/WAI/eval/report-tool
using the button:
&nbsp;&nbsp;&nbsp; **[ Open Report ]**

_(The button in Step 4 [Import data (EARL as JASON-LD)] is different. That's for if an evaluation tool gave you a report in the [Evaluation and Report Language (EARL)](https://www.w3.org/WAI/standards-guidelines/earl/).)_
